const products = [
  { id: 1, name:"Almond Croissant" , price: 2.50, category:"food",type:"bakery",popular:true, image:" images/Menu/bakery/Almond_Croissant.png"},
  { id: 2, name:"Bagel Cheese Cream" , price: 2.75, category:"food",type:"bakery",popular:false, image:"images/Menu/bakery/Bagel_Cheese_Cream.png"},
  { id: 3, name:"Cinnamon Roll" , price: 2.00, category:"food",type:"bakery",popular:true, image:" images/Menu/bakery/Cinnamon_Roll.png"},
  { id: 4, name:"Pain au Chocolat" , price: 3.00, category:"food",type:"bakery",popular:false, image:" images/Menu/bakery/Pain_au_Chocolat.png"},
  { id: 5, name:"Chicken Mozarella Panini" , price: 7.50, category:"food",type:"lunch",popular:true, image:" images/Menu/Lunch/Chicken_Mozarella_Panini.png"},
  { id: 6, name:"Chicken Parmigiana" , price: 8.00, category:"food",type:"lunch",popular:false, image:"images/Menu/Lunch/Chicken_Parmigiana.png"},
  { id: 7, name:"Turkey Cranberry Brie" , price: 9.00, category:"food",type:"lunch",popular:true, image:" images/Menu/Lunch/Turkey_Cranberry_Brie.png"},
  { id: 8, name:"Wrap Chicken Avocado" , price: 8.00, category:"food",type:"lunch",popular:true, image:" images/Menu/Lunch/Wrap_Chicken_Avocado.png"},
  { id: 9, name:"Brownie" , price: 2.25, category:"food",type:"pastry",popular:true, image:" images/Menu/Pastry/Brownie.png"},
  { id: 10, name:"Cheesecake" , price: 3.00, category:"food",type:"pastry",popular:true, image:"images/Menu/Pastry/Cheesecake.png"},
  { id: 11, name:"Cream Cookie" , price: 2.00, category:"food",type:"pastry",popular:false, image:" images/Menu/Pastry/Cream_Cookie.png"},
  { id: 12, name:"Macarons" , price: 3.50, category:"food",type:"pastry",popular:true, image:" images/Menu/Pastry/Macarons.png"},
  { id: 13, name:"Americano" , price: 2.50, category:"beverage",type:"hot",popular:true, image:" images/Menu/Hot/Americano.png"},
  { id: 14, name:"Caffè Latte" , price: 2.75, category:"beverage",type:"hot",popular:true, image:"images/Menu/Hot/Caffè_Latte.png"},
  { id: 15, name:"Cappuccino" , price: 2.00, category:"beverage",type:"hot",popular:false, image:" images/Menu/Hot/Cappuccino.png"},
  { id: 16, name:"Caramel Macchiato" , price: 3.00, category:"beverage",type:"hot",popular:true, image:" images/Menu/Hot/Caramel_Macchiato.png"},
  { id: 17, name:"Americano" , price: 3.50, category:"beverage",type:"iced",popular:false, image:" images/Menu/Iced/Iced_Cappucino.png"},
  { id: 18, name:"Caffè Latte" , price: 3.80, category:"beverage",type:"iced",popular:true, image:"images/Menu/Iced/Iced_Chocolate.png"},
  { id: 19, name:"Cappuccino" , price: 3.90, category:"beverage",type:"iced",popular:false, image:" images/Menu/Iced/Iced_Espresso.png"},
  { id: 20, name:"Caramel Macchiato" , price: 3.00, category:"beverage",type:"iced",popular:true, image:" images/Menu/Iced/Iced_Latte.png"},
  { id: 21, name:"Americano" , price: 3.50, category:"beverage",type:"refreshers",popular:false, image:" images/Menu/Refreshers/Dragon_Drink.png"},
  { id: 22, name:"Caffè Latte" , price: 3.80, category:"beverage",type:"refreshers",popular:true, image:"images/Menu/Refreshers/Grapefruit_Honey.png"},
  { id: 23, name:"Cappuccino" , price: 3.90, category:"beverage",type:"refreshers",popular:false, image:" images/Menu/Refreshers/Green_Tea_Lemonade.png"},
  { id: 24, name:"Caramel Macchiato" , price: 3.00, category:"beverage",type:"refreshers",popular:true, image:" images/Menu/Refreshers/Mango_Dragonfruit.png"}
  
]